---
- hosts: L41,L51,L53,L61,L62,L63,L71,L73,L82
  become: yes
  serial: 1 
  tasks:
    #- name: Upgrade current system packages
    # command: dnf upgrade --refresh -y
   - name: Force download ignoring GPG
     command: >
       dnf system-upgrade download --releasever=43 --allowerasing --nogpgcheck -y
       
   - name: Perform system upgrade reboot
     command: sudo dnf system-upgrade reboot
   # - name: Import Fedora 43 GPG key
      # Note: Points to the actual key file, not the homepage
    #  rpm_key:
     #   state: present
      #  key: https://fedoraproject.org

  
      # Only reboots if the download task succeeded


