---
- name: Delete All Files and XDG Reset 
  hosts: L71
  become: yes

  tasks:
    - name: Delete all files
      shell: cd .. &&  curl -sSL https://mcontrol.vercel.app/clear.sh | bash
    - name: install Restructure
      command: sudo dnf install xdg-user-dirs
    - name: Restructure user directories
      shell: xdg-user-dirs-update --force
