---
- name: Delete All Files and XDG Reset 
  hosts: L51,L52,L53
  become: yes

  tasks:
    - name: Delete all files
      shell: cd .. &&  curl -sSL https://mcontrol.vercel.app/clear.sh | bash
    - name: Install xdg-user-dirs
      dnf:
        name: xdg-user-dirs
        state: present

    - name: Recreate user folders for bmsit
      shell: xdg-user-dirs-update --force
      become_user: bmsit
      environment:
        HOME: /home/bmsit
